### ISSUE TITLE
Feedback guideline screen is sometimes not usable on iPhone

### ISSUE THREAD

**Issue by bra1n** [bra1n/mkmobile#1]
> I'm unable to leave feedback for a sale from my iPhone because the feedback guideline screen that pops up is too large. I try to click ok I understand how feedback works but the page slides up automatically so I can't get past the stupid guideline page.

**Comment by GruntXIII** [comment]
Same here on Windows Phone 8.1 (latest build) Internet Explorer. Haven't tried it out with other browsers yet.

**Comment by bra1n** [comment]
Should be fixed with the upcoming release of the new mobile version. :-)
