### ISSUE TITLE
Login form

### ISSUE THREAD

**Issue by davidmfritz** [bra1n/mkmobile#2]
Please increase the login fields and button to min-width and min-height of 48px and add proper spacing. Thanks.

**Comment by bra1n** [comment]
Hi @davidmfritz, thanks for the report! The login form is loaded in an IFrame directly from the Magiccardmarket servers, so there is nothing I can do on my end to fix this.
However, the new version 2.0 (which is currently in alpha) will have a new login form design, which you can [check out here](https://sandbox.mkmapi.eu/ws/v2.0/authenticate/alb03sLPpFNAhi6f/en). Will that solve your problem? :-)

**Comment by davidmfritz** [comment]
Looks good to me. Looking forward to the new version. Best regards

**Comment by bra1n** [comment]
Alright then, will be resolved with the new API release.
