### ISSUE TITLE
Evaluation Guidelines do not disappear 

### ISSUE THREAD

**Issue by DeviDarkL** [bra1n/mkmobile#3]
In the mobile website when I confirm a received order evaluation guidelines appear and there is no button to make them disappear making it impossible to evaluate. I am on Internet Explorer for windows phone 8.1

**Comment by radj12** [comment]
I have the same problem, also I cannot find the received button on the normal website.

**Comment by bra1n** [comment]
@radj12 you mean the "Received" button on the desktop website?

**Comment by radj12** [comment]
Yep

**Comment by bra1n** [comment]
@radj12 Then you should contact support. This issue tracker here is only for issues in the mobile app. The Evaluation Guidelines bug will be fixed in the next release of the mobile app, which will hopefully be deployed in the next month.

**Comment by radj12** [comment]
As I said it's also a problem on the mobile app

**Comment by radj12** [comment]
In the mobile when I confirm a received order evaluation guidelines appear and there is no button to make them disappear making it impossible to evaluate. I am on Internet Explorer for windows phone 8.1

**Comment by radj12** [comment]
Anyway thanks for the answer I will wait till the next release

**Comment by HendrysTobar** [comment]
When the evaluation guidelinea appear you can scroll down to see a "continue" button. But it is too far away and when you scroll down to show it you have to hold the window or the button goes down again. You cant click it while holding it and you cant click it while bor holding it because it does not show. 

It should be an easy fix. Please fix it.

**Comment by bra1n** [comment]
The new version is coming along nicely and should be ready for release soon. Please be just a bit more patient. :)

**Comment by bra1n** [comment]
Fixed in the upcoming release.
