### ISSUE TITLE
can't get into the website

### ISSUE THREAD

**Issue by user120310** [bra1n/mkmobile#9]
i made an account but i cant get into the website because the button to send the activation code dont work when i click it can you help me with this?

**Comment by bra1n** [comment]
@user120310 You can always try activating your account on the desktop page, if the app seems to be causing problems: http://www.magiccardmarket.eu

**Comment by user120310** [comment]
I was doing it on my destop didn't work


On 3 Dec 2016 6:14 p.m., Steffen <notifications@github.com> wrote:

@user120310<https://github.com/user120310> You can always try activating your account on the desktop page, if the app seems to be causing problems: http://www.magiccardmarket.eu

**Comment by bra1n** [comment]
Was there an error message? What exactly didn't work?

**Comment by user120310** [comment]
Well I can log in but after I log in I was asked to enter the activation code and I enter the code but when i click on the button that says "submit code" nothing happens

On 3 Dec 2016 6:35 p.m., Steffen <notifications@github.com> wrote:

Was there an error message? What exactly didn't work?

**Comment by bra1n** [comment]
If it also doesn't work on the desktop site, then it seems to be a problem with your account. (instead of the mobile app) In that case, I'd suggest contacting support@magiccardmarket.eu or here: https://www.magiccardmarket.eu/?mainPage=showContactForm
